export const books: IBooks[] = [
  {
    id: "1",
    title: "Darafify",
    author: "Ntaolo",
    synopsis:
      "The tale of Darafify tells of a giant whose fall into the ocean created a beautiful blue island. Over time, the island turned red, symbolizing the destruction of nature and the consequences of human actions, particularly deforestation",
    publicationDate: "12 august 2024",
    link: "https://simplebooklet.com/blueandgreenwatercolorseail",
    image: "https://iili.io/dVq17Ub.png",
    genre: "Drama",
  },
  {
    id: "2",
    title: "The birds chose a King",
    author: "Ntaolo",
    synopsis:
      "The birds decided to choose a king. The hawk was rejected for being too aggressive, so the hoopoe, known for its beauty and unique sounds, was chosen instead. The owl, absent during the selection, remains hunted by other birds",
    publicationDate: "13 august 2024",
    link: "https://simplebooklet.com/colorfulwatercolorcreateyour64#page=1",
    image: "https://iili.io/dVOZskP.jpg",
    genre: "Fantasy",
  },
  {
    id: "3",
    title: "A day at the parks",
    author: "Richard",
    synopsis:
      "The story is about a girl named Anna. She goes to the park on a sunny day. She reads a book and sees children playing. A small dog runs to her. She talks to the dog's kind owner. Anna feels happy and thinks about the simple joys in life.",
    publicationDate: "10 august 2024",
    link: "https://simplebooklet.com/adayatthepark",
    image: "https://iili.io/dVxS0mv.png",
    genre: "Drama",
  },
  {
    id: "4",
    title: "the love tree",
    author: "Richard",
    synopsis:
      '"The Love Tree"" is a story about Lily and Max, two best friends. They visit a magical tree that grows with love. As their friendship grows, so does the tree, showing how love and kindness make everything stronger and more beautiful',
    publicationDate: "13 august 2024",
    link: "https://app.bookcreator.com/read/library/-O4nKuKTGjKwW_TOk9vl/gPRDXWA0b1h0ZvifMxkkehViB5i1/UJv5HHyVRsewJ_crfHQiQQ?/Zo2CcOxUS-Wh4mqrsMSmQw",
    image: "https://iili.io/dVIFTzJ.png",
    genre: "Drama",
  },
  {
    id: "5",
    title: "Darafify",
    author: "Ntaolo",
    synopsis:
      "The tale of Darafify tells of a giant whose fall into the ocean created a beautiful blue island. Over time, the island turned red, symbolizing the destruction of nature and the consequences of human actions, particularly deforestation",
    publicationDate: "12 august 2024",
    link: "https://simplebooklet.com/blueandgreenwatercolorseail",
    image: "https://iili.io/dVq17Ub.png",
    genre: "Drama",
  },
  {
    id: "6",
    title: "The birds chose a King",
    author: "Ntaolo",
    synopsis:
      "The birds decided to choose a king. The hawk was rejected for being too aggressive, so the hoopoe, known for its beauty and unique sounds, was chosen instead. The owl, absent during the selection, remains hunted by other birds",
    publicationDate: "13 august 2024",
    link: "https://simplebooklet.com/colorfulwatercolorcreateyour64#page=1",
    image: "https://iili.io/dVOZskP.jpg",
    genre: "Fantasy",
  },
  {
    id: "7",
    title: "A day at the parks",
    author: "Richard",
    synopsis:
      "The story is about a girl named Anna. She goes to the park on a sunny day. She reads a book and sees children playing. A small dog runs to her. She talks to the dog's kind owner. Anna feels happy and thinks about the simple joys in life.",
    publicationDate: "10 august 2024",
    link: "https://simplebooklet.com/adayatthepark",
    image: "https://iili.io/dVxS0mv.png",
    genre: "Drama",
  },
  {
    id: "8",
    title: "the love tree",
    author: "Richard",
    synopsis:
      '"The Love Tree"" is a story about Lily and Max, two best friends. They visit a magical tree that grows with love. As their friendship grows, so does the tree, showing how love and kindness make everything stronger and more beautiful',
    publicationDate: "13 august 2024",
    link: "https://app.bookcreator.com/read/library/-O4nKuKTGjKwW_TOk9vl/gPRDXWA0b1h0ZvifMxkkehViB5i1/UJv5HHyVRsewJ_crfHQiQQ?/Zo2CcOxUS-Wh4mqrsMSmQw",
    image: "https://iili.io/dVIFTzJ.png",
    genre: "Drama",
  },
  {
    id: "10",
    title: "The birds chose a King",
    author: "Ntaolo",
    synopsis:
      "The birds decided to choose a king. The hawk was rejected for being too aggressive, so the hoopoe, known for its beauty and unique sounds, was chosen instead. The owl, absent during the selection, remains hunted by other birds",
    publicationDate: "13 august 2024",
    link: "https://simplebooklet.com/colorfulwatercolorcreateyour64#page=1",
    image: "https://iili.io/dVOZskP.jpg",
    genre: "Fantasy",
  },
  {
    id: "9",
    title: "Darafify",
    author: "Ntaolo",
    synopsis:
      "The tale of Darafify tells of a giant whose fall into the ocean created a beautiful blue island. Over time, the island turned red, symbolizing the destruction of nature and the consequences of human actions, particularly deforestation",
    publicationDate: "12 august 2024",
    link: "https://simplebooklet.com/blueandgreenwatercolorseail",
    image: "https://iili.io/dVq17Ub.png",
    genre: "Drama",
  },
  {
    id: "11",
    title: "A day at the parks",
    author: "Richard",
    synopsis:
      "The story is about a girl named Anna. She goes to the park on a sunny day. She reads a book and sees children playing. A small dog runs to her. She talks to the dog's kind owner. Anna feels happy and thinks about the simple joys in life.",
    publicationDate: "10 august 2024",
    link: "https://simplebooklet.com/adayatthepark",
    image: "https://iili.io/dVxS0mv.png",
    genre: "Drama",
  },
  {
    id: "12",
    title: "the love tree",
    author: "Richard",
    synopsis:
      '"The Love Tree"" is a story about Lily and Max, two best friends. They visit a magical tree that grows with love. As their friendship grows, so does the tree, showing how love and kindness make everything stronger and more beautiful',
    publicationDate: "13 august 2024",
    link: "https://app.bookcreator.com/read/library/-O4nKuKTGjKwW_TOk9vl/gPRDXWA0b1h0ZvifMxkkehViB5i1/UJv5HHyVRsewJ_crfHQiQQ?/Zo2CcOxUS-Wh4mqrsMSmQw",
    image: "https://iili.io/dVIFTzJ.png",
    genre: "Drama",
  },
  {
    id: "13",
    title: "Darafify",
    author: "Ntaolo",
    synopsis:
      "The tale of Darafify tells of a giant whose fall into the ocean created a beautiful blue island. Over time, the island turned red, symbolizing the destruction of nature and the consequences of human actions, particularly deforestation",
    publicationDate: "12 august 2024",
    link: "https://simplebooklet.com/blueandgreenwatercolorseail",
    image: "https://iili.io/dVq17Ub.png",
    genre: "Drama",
  },
  {
    id: "14",
    title: "The birds chose a King",
    author: "Ntaolo",
    synopsis:
      "The birds decided to choose a king. The hawk was rejected for being too aggressive, so the hoopoe, known for its beauty and unique sounds, was chosen instead. The owl, absent during the selection, remains hunted by other birds",
    publicationDate: "13 august 2024",
    link: "https://simplebooklet.com/colorfulwatercolorcreateyour64#page=1",
    image: "https://iili.io/dVOZskP.jpg",
    genre: "Fantasy",
  },
  {
    id: "16",
    title: "the love tree",
    author: "Richard",
    synopsis:
      '"The Love Tree"" is a story about Lily and Max, two best friends. They visit a magical tree that grows with love. As their friendship grows, so does the tree, showing how love and kindness make everything stronger and more beautiful',
    publicationDate: "13 august 2024",
    link: "https://app.bookcreator.com/read/library/-O4nKuKTGjKwW_TOk9vl/gPRDXWA0b1h0ZvifMxkkehViB5i1/UJv5HHyVRsewJ_crfHQiQQ?/Zo2CcOxUS-Wh4mqrsMSmQw",
    image: "https://iili.io/dVIFTzJ.png",
    genre: "Drama",
  },
  {
    id: "15",
    title: "A day at the parks",
    author: "Richard",
    synopsis:
      "The story is about a girl named Anna. She goes to the park on a sunny day. She reads a book and sees children playing. A small dog runs to her. She talks to the dog's kind owner. Anna feels happy and thinks about the simple joys in life.",
    publicationDate: "10 august 2024",
    link: "https://simplebooklet.com/adayatthepark",
    image: "https://iili.io/dVxS0mv.png",
    genre: "Drama",
  },
  {
    id: "20",
    title: "the love tree",
    author: "Richard",
    synopsis:
      '"The Love Tree"" is a story about Lily and Max, two best friends. They visit a magical tree that grows with love. As their friendship grows, so does the tree, showing how love and kindness make everything stronger and more beautiful',
    publicationDate: "13 august 2024",
    link: "https://app.bookcreator.com/read/library/-O4nKuKTGjKwW_TOk9vl/gPRDXWA0b1h0ZvifMxkkehViB5i1/UJv5HHyVRsewJ_crfHQiQQ?/Zo2CcOxUS-Wh4mqrsMSmQw",
    image: "https://iili.io/dVIFTzJ.png",
    genre: "Drama",
  },
  {
    id: "21",
    title: "Darafify",
    author: "Ntaolo",
    synopsis:
      "The tale of Darafify tells of a giant whose fall into the ocean created a beautiful blue island. Over time, the island turned red, symbolizing the destruction of nature and the consequences of human actions, particularly deforestation",
    publicationDate: "12 august 2024",
    link: "https://simplebooklet.com/blueandgreenwatercolorseail",
    image: "https://iili.io/dVq17Ub.png",
    genre: "Drama",
  },
  {
    id: "18",
    title: "The birds chose a King",
    author: "Ntaolo",
    synopsis:
      "The birds decided to choose a king. The hawk was rejected for being too aggressive, so the hoopoe, known for its beauty and unique sounds, was chosen instead. The owl, absent during the selection, remains hunted by other birds",
    publicationDate: "13 august 2024",
    link: "https://simplebooklet.com/colorfulwatercolorcreateyour64#page=1",
    image: "https://iili.io/dVOZskP.jpg",
    genre: "Fantasy",
  },
  {
    id: "17",
    title: "Darafify",
    author: "Ntaolo",
    synopsis:
      "The tale of Darafify tells of a giant whose fall into the ocean created a beautiful blue island. Over time, the island turned red, symbolizing the destruction of nature and the consequences of human actions, particularly deforestation",
    publicationDate: "12 august 2024",
    link: "https://simplebooklet.com/blueandgreenwatercolorseail",
    image: "https://iili.io/dVq17Ub.png",
    genre: "Drama",
  },
  {
    id: "19",
    title: "A day at the parks",
    author: "Richard",
    synopsis:
      "The story is about a girl named Anna. She goes to the park on a sunny day. She reads a book and sees children playing. A small dog runs to her. She talks to the dog's kind owner. Anna feels happy and thinks about the simple joys in life.",
    publicationDate: "10 august 2024",
    link: "https://simplebooklet.com/adayatthepark",
    image: "https://iili.io/dVxS0mv.png",
    genre: "Drama",
  },
  {
    id: "22",
    title: "The birds chose a King",
    author: "Ntaolo",
    synopsis:
      "The birds decided to choose a king. The hawk was rejected for being too aggressive, so the hoopoe, known for its beauty and unique sounds, was chosen instead. The owl, absent during the selection, remains hunted by other birds",
    publicationDate: "13 august 2024",
    link: "https://simplebooklet.com/colorfulwatercolorcreateyour64#page=1",
    image: "https://iili.io/dVOZskP.jpg",
    genre: "Fantasy",
  },
  {
    id: "23",
    title: "A day at the parks",
    author: "Richard",
    synopsis:
      "The story is about a girl named Anna. She goes to the park on a sunny day. She reads a book and sees children playing. A small dog runs to her. She talks to the dog's kind owner. Anna feels happy and thinks about the simple joys in life.",
    publicationDate: "10 august 2024",
    link: "https://simplebooklet.com/adayatthepark",
    image: "https://iili.io/dVxS0mv.png",
    genre: "Drama",
  },
  {
    id: "24",
    title: "the love tree",
    author: "Richard",
    synopsis:
      '"The Love Tree"" is a story about Lily and Max, two best friends. They visit a magical tree that grows with love. As their friendship grows, so does the tree, showing how love and kindness make everything stronger and more beautiful',
    publicationDate: "13 august 2024",
    link: "https://app.bookcreator.com/read/library/-O4nKuKTGjKwW_TOk9vl/gPRDXWA0b1h0ZvifMxkkehViB5i1/UJv5HHyVRsewJ_crfHQiQQ?/Zo2CcOxUS-Wh4mqrsMSmQw",
    image: "https://iili.io/dVIFTzJ.png",
    genre: "Drama",
  },
  {
    id: "25",
    title: "Darafify",
    author: "Ntaolo",
    synopsis:
      "The tale of Darafify tells of a giant whose fall into the ocean created a beautiful blue island. Over time, the island turned red, symbolizing the destruction of nature and the consequences of human actions, particularly deforestation",
    publicationDate: "12 august 2024",
    link: "https://simplebooklet.com/blueandgreenwatercolorseail",
    image: "https://iili.io/dVq17Ub.png",
    genre: "Drama",
  },
  {
    id: "26",
    title: "The birds chose a King",
    author: "Ntaolo",
    synopsis:
      "The birds decided to choose a king. The hawk was rejected for being too aggressive, so the hoopoe, known for its beauty and unique sounds, was chosen instead. The owl, absent during the selection, remains hunted by other birds",
    publicationDate: "13 august 2024",
    link: "https://simplebooklet.com/colorfulwatercolorcreateyour64#page=1",
    image: "https://iili.io/dVOZskP.jpg",
    genre: "Fantasy",
  },
  {
    id: "27",
    title: "A day at the parks",
    author: "Richard",
    synopsis:
      "The story is about a girl named Anna. She goes to the park on a sunny day. She reads a book and sees children playing. A small dog runs to her. She talks to the dog's kind owner. Anna feels happy and thinks about the simple joys in life.",
    publicationDate: "10 august 2024",
    link: "https://simplebooklet.com/adayatthepark",
    image: "https://iili.io/dVxS0mv.png",
    genre: "Drama",
  },
  {
    id: "28",
    title: "the love tree",
    author: "Richard",
    synopsis:
      '"The Love Tree"" is a story about Lily and Max, two best friends. They visit a magical tree that grows with love. As their friendship grows, so does the tree, showing how love and kindness make everything stronger and more beautiful',
    publicationDate: "13 august 2024",
    link: "https://app.bookcreator.com/read/library/-O4nKuKTGjKwW_TOk9vl/gPRDXWA0b1h0ZvifMxkkehViB5i1/UJv5HHyVRsewJ_crfHQiQQ?/Zo2CcOxUS-Wh4mqrsMSmQw",
    image: "https://iili.io/dVIFTzJ.png",
    genre: "Drama",
  },
];
